#Яркость
bind = , XF86MonBrightnessUp, exec, brightnessctl set +10%
bind = , XF86MonBrightnessDown, exec, brightnessctl set 10%-

bind = , XF86AudioRaiseVolume, exec, pactl list short sinks | awk '{print $2}' | xargs -I{} pactl set-sink-volume {} +5%
bind = ,XF86AudioLowerVolume, exec, pactl list short sinks | awk '{print $2}' | xargs -I{} pactl set-sink-volume {} -5%
bind = ,XF86AudioMute, exec, pactl list short sinks | awk '{print $2}' | xargs -I{} pactl set-sink-mute {} toggle
