#
# ~/.config/hypr/hyprland.conf
# Базовый конфиг — только общие параметры
#

$configs = $HOME/.config/hypr/configs
$userConfigs = $HOME/.config/hypr/UserConfigs

source = $HOME/.config/hypr/initial_boot.sh

# --- Общие настройки ---

source = $userConfigs/UserDefault.conf
source = $userConfigs/UserSettings.conf
source = $userConfigs/UserKeybinds.conf

input {
    kb_layout = us,ru
    kb_variant =
    kb_model =
    kb_options = grp:win_space_toggle
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}


# --- Мониторы ---
monitor=eDP-1, 1920x1200@60.00200, 0x0, 1

# --- Подключаем keybinds ---
source = $configs/keybinds.conf
exec-once = sudo /home/mediees/.config/hypr/fix_sound.sh
